application:
  prefixes:
  - name: _route
  - name: _compensation
  routes:
  - id: rt_20220523010636
    index: 2
  service:
    name: member

server:
  port: 1007
  servlet:
    context-path: /${application.service.name}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:  # runner와 연동되어 있는 kafka 리소스를 연결합니다
    bootstrapServers: localhost:9092
    consumer:
      enable-auto-commit: true
      group-id: ${application.routes[0].id}-${application.routes[0].index}
    producer:
      valueSerializer: com.msamaker.demo.saga.model.ObjectSerializer
